apiVersion: v1
kind: Service
metadata:
  name: coffee-app-lb-service
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  selector:
      app: coffee-app
  type: LoadBalancer
status:
  loadBalancer: { }