apiVersion: v1
kind: Pod
metadata:
  name: coffee-app
spec:
  containers:
    - image: docker.io/igorsakhankov/harbourspace_cloudcomputing:latest
      name: coffee-app
      env:
        - name: "AWS_KEY_ID"
          valueFrom:
            configMapKeyRef:
              name: harbour-config
              key: AWS_KEY_ID
        - name: "AWS_REGION"
          valueFrom:
            configMapKeyRef:
              name: harbour-config
              key: AWS_REGION
        - name: "AWS_SECRET"
          valueFrom:
            configMapKeyRef:
              name: harbour-config
              key: AWS_SECRET
        - name: "CLUSTER_API_KEY"
          valueFrom:
              configMapKeyRef:
                name: harbour-config
                key: CLUSTER_API_KEY
        - name: "CLUSTER_API_SECRET"
          valueFrom:
              configMapKeyRef:
                name: harbour-config
                key: CLUSTER_API_SECRET
      resources:
        requests:
          cpu: "1"
          memory: "1024Mi"
        limits:
          cpu: "2"
          memory: "2048Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP